---
- name: "{{ install_name }} installation and configuration"
  hosts: "{{ hosts_group_name | default('all') }}"
  remote_user: root
  vars:
    wildfly_install_workdir: '/opt'
    install_name: "{{ override_install_name | default('wildfly') }}"
    wildfly_user: "{{ install_name }}"
    wildfly_config_base: standalone-ha.xml
    wildfly_home: "{{ wildfly_install_workdir }}/{{ install_name }}-{{ wildfly_version }}"
    instance_http_ports:
      - 8080
      - 8180
      - 8280
    app:
      name: 'helloworld.war'
      url: 'https://drive.google.com/uc?export=download&id=16HOaSVF0bSYyjc8a8hkEiDlTqgJuGJfe'
    ansible_distribution: 'RedHat'
  collections:
    - middleware_automation.wildfly
  roles:
    - wildfly_install
  tasks:

    - name: "Set up for Wildfly instance {{ item }}"
      include_role:
        name: wildfly_systemd
      vars:
        wildfly_config_base: 'standalone-ha.xml'
        wildfly_basedir_prefix: "/opt/{{ install_name }}-{{ item }}"
        wildfly_config_name: "{{ install_name }}-{{ item }}"
        wildfly_instance_name: "{{ install_name }}-{{ item }}"
        wildfly_instance_id: "{{ item }}"
        service_systemd_env_file: "/etc/{{ install_name }}-{{ item }}.conf"
        service_systemd_conf_file: "/usr/lib/systemd/system/{{ install_name }}-{{ item }}.service"
        wildfly_port_range_offset: "{{ 100 * (item) | int }}"
      loop: "{{ range(0,3) | list }}"

    - name: "Ensures webapp {{ app.name }} has been retrieved from {{ app.url }}"
      become: true
      ansible.builtin.get_url:
        url: "{{ app.url }}"
        dest: "{{ wildfly_install_workdir }}/{{ app.name }}"

    - name: "Determine info app absolute path."
      ansible.builtin.set_fact:
        info_app_dest: "{{ wildfly_install_workdir }}/{{ app.name }}"

    - name: "Fine tuning configuration: {{ install_name }}"
      ansible.builtin.include_role:
        name: wildfly_utils
        tasks_from: jboss_cli.yml
      vars:
        jboss_home: "{{ wildfly_home }}"
        jboss_cli_query: "'deploy --force {{ wildfly_install_workdir }}/{{ app.name }}'"
        jboss_cli_controller_port: "{{ item }}"
      loop:
        - 10090
        - 10190

  post_tasks:
    - name: "Verify that deployments are functional."
      ansible.builtin.include_tasks: validate.yml
      loop: "{{ instance_http_ports }}"
