---
dependency:
  name: galaxy
#  options:
#    requirements-file: molecule/default/requirements.yml
driver:
  name: docker
platforms:
  - name: instance
    image: registry.access.redhat.com/ubi8/ubi-init
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd log-level=info unit=sysinit.target"
    pre_build_image: true
    privileged: true
    port_bindings:
      - 8080:8080
    published_ports:
      - 0.0.0.0:8080:8080/TCP
    groups:
      - wildfly
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
  inventory:
    all:
      hosts_group_name: wildfly
  playbooks:
    prepare: prepare.yml
    converge: ../../playbook.yml
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
