---
dependency:
  name: shell
  command: ansible-galaxy collection install -r molecule/default/requirements.yml -p $HOME/.ansible/collections --force-with-deps
driver:
  name: docker
platforms:
  - name: instance
    image: centos:8
    privileged: true
    groups:
      - wildfly
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd log-level=info unit=sysinit.target"
    port_bindings:
      - 8080:8080
    published_ports:
      - 0.0.0.0:8080:8080/TCP
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
  ansible_args:
    - "-e hosts_group_name='wildfly'"
  inventory:
    all:
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
    group_vars:
      wildfly:
        install_name: 'Molecule'
  playbooks:
    converge: ../../playbook.yml
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
      #- idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
