---
name: CI
"on":
  push:
    branches:
      - main
  pull_request:
  repository_dispatch:

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.11"]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: /home/runner/work/wildfly-cluster-demo/wildfly-cluster-demo

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install yamllint, ansible and molecule
        run: |
          python -m pip install --upgrade pip
          pip install yamllint 'molecule>=6.0.3' 'molecule-plugins[docker]>=23.5.3' ansible-core flake8 ansible-lint voluptuous

      - name: Run molecule test
        run: |
          ansible-galaxy collection install -r molecule/default/requirements.yml
          molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
